name: github workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome Message
          run: echo "My first file"
        - name: List the file
          run: echo "ls -la"
        - name: display readme file
          run: cat README.md
          
