name: github workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4
        - name: Welcome Message
          run: touch ${{ secrets.FILE_NAME }}
        - uses: actions/upload-artifact@v4
          with:
            name: sample-artifact
            path: ${{ secrets.FILE_NAME }}
    second_job:
       needs: first_job
       runs-on: ubuntu-latest
       steps:
        - uses: actions/download-artifact@v4
          with:
           name: sample-artifact
        - name: Display structure of downloaded files
          run: ls -R


