name: github workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4
        - name: Welcome Message
          run: cat vamsi.txt
    second_job:
       needs: first_job
       runs-on: ubuntu-latest
       steps:
        - name: display cat file
          run: cat vamsi.txt
          

