name: github workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4
        - name: Welcome Message
          run: echo "My first file"
        - name: List the file
          run: |
              echo " Hi Vamsi"
              ls -ltr
              cat README.md
        - name: run shell script
          run: sh shell-script-asc.sh
       

